#!/bin/sh

#############MANDATORY#########
PROJECT_NAME=
###############################

if [ -z "$DOCKERHUB_USER" ]; then
  DOCKERHUB_USER='codelittinc'
fi

if [ -z "$DEPLOY_TYPE" ]; then
  exit "You need to pass the deploy type(DEPLOY_TYPE), example: qa, production, beta, etc."
fi

if [ -z "$SERVER_USER" ]; then
  exit "You need to pass the server username (SERVER_USER) for the deployment of this application."
fi

if [ -z "$SERVER_HOST" ]; then
  exit "You need to pass the server hostname (SERVER_HOST) for the deployment of this application."
fi

CONTAINER_NAME=$PROJECT_NAME-$DEPLOY_TYPE
SSH_CMD="ssh $SERVER_USER@$SERVER_HOST"

generate_and_push_image(){
  sh bin/build && docker push '$DOCKERHUB_USER/$PROJECT_NAME'
}

init(){

generate_and_push_image

DEPLOY_COMMAND="""
docker pull $DOCKERHUB_USER/$PROJECT_NAME;
docker rm \$(docker ps -a -q -f name=previous-$CONTAINER_NAME);
docker stop \$(docker ps -a -q -f name=$CONTAINER_NAME);
docker rename $CONTAINER_NAME previous-$CONTAINER_NAME;
docker run --name $CONTAINER_NAME
-p 3000:3000 -p 4000:4000 -d $DOCKERHUB_USER/$PROJECT_NAME:latest"""

#To pass environment variable put then in this format and before the last line of the text above:
#example:
#-e GLX_DATABASE_PASSWORD=------- \
#-e GLX_DATABASE_USER=------- \
#-e GLX_DATABASE_HOST=0.0.0.0

$SSH_CMD $DEPLOY_COMMAND
}

init